# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eedebc66f4e570b878eb4244e8c30a0a794c4abb4037004a61c949909dfeaa2f83bdd895b2290aefedccffe413ef255c72b389b1bc62c395b6844d8841f107e4

test:
  secret_key_base: 11d7bc2307e573bde9b5325a27bc31a034e661c4c4b60d3e8782449206a4faec7f6ae39df4e037620cf36fa851cc4a1d3131b83c3e804604e1f3c2a3dce07c9a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
